USE [master]
GO

/****** Object:  Database [BeenThere]    Script Date: 18-Sep-17 13:04:04 ******/
CREATE DATABASE [BeenThere]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'BeenThere', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\BeenThere.mdf' , SIZE = 4096KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'BeenThere_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\BeenThere_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [BeenThere] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [BeenThere].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [BeenThere] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [BeenThere] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [BeenThere] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [BeenThere] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [BeenThere] SET ARITHABORT OFF 
GO

ALTER DATABASE [BeenThere] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [BeenThere] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [BeenThere] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [BeenThere] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [BeenThere] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [BeenThere] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [BeenThere] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [BeenThere] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [BeenThere] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [BeenThere] SET  DISABLE_BROKER 
GO

ALTER DATABASE [BeenThere] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [BeenThere] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [BeenThere] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [BeenThere] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [BeenThere] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [BeenThere] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [BeenThere] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [BeenThere] SET RECOVERY FULL 
GO

ALTER DATABASE [BeenThere] SET  MULTI_USER 
GO

ALTER DATABASE [BeenThere] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [BeenThere] SET DB_CHAINING OFF 
GO

ALTER DATABASE [BeenThere] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [BeenThere] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [BeenThere] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [BeenThere] SET  READ_WRITE 
GO

